# Generated by Django 4.1 on 2022-09-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_comment_is_enable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_enable",
        ),
    ]
